config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'questions#index'
  resources :questions, shallow: true do
    resources :answers, shallow: true do
      member do
        patch :best
      end
    end
  end
  resources :links, only: :destroy
  resources :attachments, only: :destroy
  resources :rewards, only: :index
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :user

  has_many :links, dependent: :destroy, as: :linkable

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true

  validates :body, presence: true

  def mark_as_best
    Answer.transaction do
      Answer.where(question_id: question_id, best: true).update_all(best: false)
      update!(best: true)
      question.reward&.update!(user: user)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :linkable, polymorphic: true

  validates :name, :url, presence: true
  validates :url, url: { no_local: true, schemes: %w[http https], public_suffix: true }

  def gist?
    URI.parse(url).host&.include?('gist')
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :user

  has_many :answers, -> { order(best: :desc) }, dependent: :destroy
  has_many :links, dependent: :destroy, as: :linkable

  has_one :reward, dependent: :destroy

  has_many_attached :files

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :reward, reject_if: :all_blank, allow_destroy: true

  validates :body, :title, presence: true
end

app/models/reward.rb
class Reward < ApplicationRecord
  belongs_to :question
  belongs_to :user, optional: true

  has_one_attached :image

  validates :title, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :answers, dependent: :destroy
  has_many :questions, dependent: :destroy
  has_many :rewards, dependent: :destroy

  def author_of?(post)
    self == post.user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :authenticate_user!
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[destroy update best]

  def new
    @answer = @question.answers.new
  end

  def create
    @answer = @question.answers.new(answer_params)
    @answer.user = current_user
    @answer.save
  end

  def update
    @answer.update(answer_params)
    @question = @answer.question
  end

  def destroy
    if current_user.author_of?(@answer)
      @answer.destroy
      redirect_to @answer.question, notice: 'You have successfully remove answer'
    else
      flash[:notice] = 'Failed to delete question'
    end
  end

  def best
    @question = @answer.question
    @answer.mark_as_best if current_user.author_of?(@question)
  end

  private

  def find_answer
    @answer = Answer.with_attached_files.find(params[:id])
  end

  def find_question
    @question = Question.find(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body, files: [], links_attributes: %i[name url])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/attachments_controller.rb
class AttachmentsController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @file = ActiveStorage::Attachment.find(params[:id])
    @file.purge if current_user&.author_of?(@file.record)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :authenticate_user!

  def destroy
    @link = Link.find(params[:id])
    @link.destroy if current_user&.author_of?(@link.linkable)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :load_question, only: %i[show edit update destroy]

  def index
    @questions = Question.all
  end

  def show
    @answer = @question.answers.new
    @answer.links.new
  end

  def new
    @question = Question.new
    @question.links.new
    @question.build_reward
  end

  def edit; end

  def create
    @question = Question.new(question_params)
    @question.user = current_user
    if @question.save
      redirect_to @question, notice: 'Your question successfully created.'
    else
      render :new
    end
  end

  def update
    @question.update(question_params)
  end

  def destroy
    if current_user.author_of?(@question)
      @question.destroy
      redirect_to questions_path, notice: 'You have successfully remove question'
    else
      flash[:notice] = 'Failed to delete question'
    end
  end

  private

  def load_question
    @question = Question.with_attached_files.find(params[:id])
  end

  def question_params
    params.required(:question).permit(:title, :body, files: [],
                                                     links_attributes: %i[name url],
                                                     reward_attributes: %i[title image])
  end
end

app/controllers/rewards_controller.rb
class RewardsController < ApplicationController
  before_action :authenticate_user!, only: :index

  def index
    @rewards = current_user.rewards
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/rewards_helper.rb
module RewardsHelper
end

app/views/answers/_answer.html.slim
- if answer.persisted?
  .answer id="answer_#{answer.id}"
    p= answer.body
    .links
      p Links:
      ul
        =render 'shared/links', resource: answer

    = render 'shared/attachments', resource: answer

    - if user_signed_in? && current_user&.author_of?(answer.question)
      p= link_to "Best answer", best_answer_path(answer), remote: true, method: :patch

    - if user_signed_in? && answer.persisted? && current_user&.author_of?(answer)
      p= link_to "Remove Answer", answer_path(answer),   method: :delete, data: {confirm: "Are you sure?"}
      p= link_to 'Edit', '#', class: 'edit-answer-link', data: { answer_id: answer.id }

    = form_with model: answer, local: false, class: 'hidden', html: {id: "edit-answer-#{answer.id}"}, direct_upload: true do |f|
      p
        = f.label :body, 'Your answer'
        = f.text_area :body
      p
        = f.label :files
        = f.file_field :files, multiple: true
      p
        #links
          = f.fields_for :links do |l|
          .add_link
            = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

      = f.submit 'Save'

app/views/answers/_form.html.slim
.answer-errors
  = render 'shared/errors', resource: @answer
= form_with model: [@question, @answer], class: 'new-answer', local: false, direct_upload: true do |f|
  p
    = f.label :body, 'Your answer'
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true
  p
    = render 'shared/add_links', f: f

  = f.submit 'Answer'

app/views/answers/best.js.erb
<% if @answer.persisted? %>
  $('.answers').html('<%= j render @question.answers %>');
<% end %>

app/views/answers/create.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');
<% if @answer.persisted? %>
  $('.answers').append('<%= j render @answer %>');
  $('.new-answer #answer_body').val('');
<% end %>

app/views/answers/destroy.js.erb
$('.answer-errors').html('<%= render 'shared/errors', resource: @answer %>');

<% unless @answer.errors.present? %>
  $('.answers .answer-id-<%= @answer.id %>').remove();
  $('.answers').html('<%= j render @question.answers %>');
<% end %>

app/views/answers/new.html.slim
p Create Answer
= render "form"

app/views/answers/update.js.erb
<% unless @answer.errors.present? %>
  $('.answers .answer-id-<%= @answer.id %>').remove();
  $('.answers').html('<%= j render @question.answers %>');
<% else %>
  $('form#edit-answer-' + <%= @answer.id %>).append('<%= j render "shared/errors", resource: @answer %>');
<% end %>

app/views/attachments/destroy.js.erb
$('[data-file-id="<%= @file.id %>"]').remove();

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Qna
    meta[name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no"]
    meta[cahrset="utf-8"]
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = render 'shared/nav'
    p.notice
      = notice
    p.alert
      = alert
    = yield

app/views/links/destroy.js.erb
$("#link_<%= @link.id %>").remove();

app/views/questions/_form.html.slim
= render 'shared/errors', resource: @question

= form_with model: @question, direct_upload: true do |f|
  p
    = f.label :title
    = f.text_field :title
  p
    = f.label :body
    = f.text_area :body
  p
    = f.label :files
    = f.file_field :files, multiple: true

  p
    = render 'shared/add_links', f: f

  p
    = render 'reward_form', f: f

  = f.submit "Ask"

app/views/questions/_question.html.slim
tr.table-light.border-info
  td.align-middle = link_to question.title, question_path(question)
  td.align-middle = question.body

app/views/questions/_question_main.html.slim
.question
  h1= 'Question'
  .q-title
    h5= @question.title
  .q-body
    p= @question.body
  .links
  p Links:
  ul
    =render 'shared/links', resource: @question

  = render 'shared/attachments', resource: @question

  div class=["question-error-#{@question.id}"]
  - if current_user&.author_of?(@question)
    p = link_to "Remove Question", question_path(@question), method: :delete, data: {confirm: "Are you sure?"}
    p = link_to 'Edit question', '#', class: 'edit-question-link', data: { question_id: @question.id }

    = render 'shared/errors', resource: @answer
    = form_with model: @question, class: 'hidden', html: { id: "edit-question-#{@question.id}" }, local: false, direct_upload: true  do |f|
      = f.label :title
      = f.text_area :title
      = f.label :body
      = f.text_area :body
      = f.label :files
      = f.file_field :files, multiple: true
      p
        #links
          = f.fields_for :links do |l|
          .add_link
            = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'
      = f.submit 'Save'

app/views/questions/_reward_form.html.slim
p Reward
.reward
  = f.fields_for :reward do |r|
    p
      = r.label :title, 'Reward title'
      = r.text_field :title
    p
      = r.label :image
      = r.file_field :image

app/views/questions/edit.html.slim
= render 'form'

app/views/questions/index.html.slim
p= link_to  "Ask question", new_question_path
p= link_to  "Rewards", rewards_path
p Questions:
table.table.table-bordered.text-center
  tr.table-primary.border-primary
    th Title
    th Body
  = render @questions

app/views/questions/new.html.slim
= render 'form'

app/views/questions/show.html.slim
= render 'question_main'


.answers
  h2 Answers:
  = render @question.answers

- if user_signed_in?
  p New Answer:
  = render 'answers/form'

app/views/questions/update.js.erb
$('.question .question-error-<%= @question.id %>').html('<%= render 'shared/errors', resource: @question %>');

<% unless @question.errors.present? %>
  $('.question').html("<%= j render 'question_main' %>")
<% end %>

app/views/rewards/index.html.slim
p Rewards:
- if !@rewards.empty?
  - @rewards.each do |reward|
    p
      = reward.question.title
    p
      = reward.title
    p
      = image_tag reward.image, size: "150x150" if reward.image.attached?
- else
  p= "- You don't have awards"

app/views/shared/_add_links.html.slim
p Links:
#links
  = f.fields_for :links do |l|
    = render 'shared/link_fields', f: l
  .add_links
  = link_to_add_association 'add link', f, :links, partial: 'shared/link_fields'

app/views/shared/_attachments.html.slim
- if resource.files.attached?
  - resource.files.each do |file|
    div data-file-id = file.id
      p= link_to file.filename.to_s, url_for(file)
      - if current_user&.author_of?(resource)
        = button_to 'Delete file', attachment_path(file), method: :delete, remote: true

app/views/shared/_errors.html.slim
- if resource&.errors.present?
  b= "#{resource.errors.count} error(s) detected: "
  ul
    -resource.errors.full_messages.each do |message|
      li= message

app/views/shared/_link_fields.html.slim
.nested-fields
  p
    =f.label :name, 'Link name'
    =f.text_field :name
  p
    =f.label :url
    =f.text_field :url
  = link_to_remove_association "remove link", f

app/views/shared/_links.html.slim
- resource.links.each do |link|
  - if link.persisted?
    div id="link_#{link.id}"
      - if link.gist?
        = link.name
        script src="#{link.url}.js"
      -else
        li= link_to link.name, link.url, target: :_blank

      - if current_user&.author_of?(resource)
        p= link_to 'Remove link', link_path(link), method: :delete, remote: true

app/views/shared/_nav.html.slim
.mt-5
  - if user_signed_in?
    = link_to "Log out", destroy_user_session_path, method: :delete, data: {confirm: 'Are you sure?'}
  - else
    = link_to "Login", new_user_session_path
    br
    = link_to "Register", new_user_registration_path